build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: WorkShift Calendar"
  org.opencontainers.image.description: "A powerful shift calendar for Home Assistant integration"
  org.opencontainers.image.source: "https://github.com/GrimReapaa420/ShiftAssistant"
  org.opencontainers.image.licenses: "MIT"
